##########################################
#  DATABASE POOL.  One for now
#  We will want an array of these things
#  in today's technology, the connection
#  pooling is done in the connection service
#  itself
##########################################
database:
  dialect: mysql
  port: 3306
  host:  192.168.0.15
  dbname: scaha
  sslMode: disable
  user: root
  password: shiloh24
  isEnabled: true

external-ms:
  isHTTPS: false
  port: 4020
